### ISSUE TITLE
PP_COMPOUND_ERROR

### ISSUE THREAD

**Issue by bongomedia** [IFL-CAMP/iiwa_stack#100]
Hi,

I did all the steps you mentioned in your wiki and when I start I get the errror message PP_COMPOUND_ERROR. I use Sunrise 1.13 and have all the servoing packages installed.
I know that this is an internal KUKA message, but maybe someome knows a solution.

Best regards

**Comment by SalvoVirga** [comment]
Did you try to start the robot from a different joint configuration or are you always starting it from the same one (maybe home position)?

**Comment by bongomedia** [comment]
Hey Salvo, this was an internal issue, which is solved by KUKA ;)

Thanks and best regards
