### ISSUE TITLE
branch for sunrise 1.9

### ISSUE THREAD

**Issue by hitli** [IFL-CAMP/iiwa_stack#106]
I‘m wondering what can i do to make master branch work on Sunrise.OS 1.9，as there are new features added to iiwa-stack.

**Comment by SalvoVirga** [comment]
From 1.9 to 1.11 I believe there were only some changes in the namespace of some functions in the KUKA APIs.

- Take the current master to Workbench 1.9, you should have some errors for some Java imports on the top of some files. 
- Delete those imports. You will get some errors in the code for some missing imports. 
- Over your mouse on the function giving the error, you should get a suggestion for the right import. 
- Repeat for all the cases around the code and you should be done.

I plan a new release for this month, I'll try to update also the 1.9 branch. But I still suggest to update to a newer version, it usually just costs an email to the KUKA support.

**Comment by SalvoVirga** [comment]
I just updated the Sunrise 1.9 with the current master, it is not tested on a real robot but everything should be working.
