### ISSUE TITLE
cast the fixes in master branch to other sunrise version branches 

### ISSUE THREAD

**Issue by jacknlliu** [IFL-CAMP/iiwa_stack#110]
The fixes in master branch are not cast to other sunrise branches, such as Master-sunrise1.7.

**Comment by SalvoVirga** [comment]
I just merged the current master to the ones for older versions of Sunrise. 
We cannot test those versions on the real robot anymore, so open an issue if needed.

That said, we always recommend to upgrade to the latest Sunrise version available when possible.
