### ISSUE TITLE
Support for Sunrise OS 1.13

### ISSUE THREAD

**Issue by breigo** [IFL-CAMP/iiwa_stack#112]
Hi there!
Has anybody expirience with running iiwa stack on Sunrise OS 1.13?

I found some hints, that it should work in a discussion about 1.15 in [issue 102](https://github.com/IFL-CAMP/iiwa_stack/issues/102)
Are there any reports about things which do not work and need adoption?

Thanks for your help.

**Comment by cjue** [comment]
Hi, #103 reported successfully working with Sunrise.OS 1.13 and 1.14.

**Comment by breigo** [comment]
Thanks for the Info.
