### ISSUE TITLE
iiwa_ros_java/src not working with Sunrise workbench (wiki instructions)

### ISSUE THREAD

**Issue by emielke12** [IFL-CAMP/iiwa_stack#115]
Hi, I am following along with the wiki instructions, and I got to the sunrise workbench portion of the instructions [https://github.com/IFL-CAMP/iiwa_stack/wiki/sunrise_project_setup](url) and I my sunrise workbench has red Xs for all the files from iiwa_ros_java/src. I've attached some screenshots. It looks like there are classes from a com.kuka.connectivity file that are missing. Additionally, I didn't see the same options for the StationSetup.cat software tab. Are these related? Is there a problem with the smartServo class? Is there a way to get the other software to show up? 
![img_0573](https://user-images.githubusercontent.com/17884820/41413305-50ef29b2-6fa8-11e8-9cd7-7a6703789b31.JPG)
![img_0574](https://user-images.githubusercontent.com/17884820/41413311-5412543e-6fa8-11e8-994d-11b24c238646.JPG)
![img_0575](https://user-images.githubusercontent.com/17884820/41413313-55e5e910-6fa8-11e8-9c56-27a568e447d6.JPG)

**Comment by SalvoVirga** [comment]
Yes, the problems are related!
You need the Sunrise.Connectivity (Sunrise.Servoing) to use iiwa_stack (or in general to control the robot at runtime). This is an additional package that you have to request from KUKA and install into the Sunrise Workbench environment.

**Comment by madhukartlr** [comment]
@SalvoVirga I have already installed the Sunrise.Connectivity using **com.kuka.connectivity.industrial.repository-1.7.0.ConnV17_2** but I am still having issues with importing Servo Motion controls. 
Thanks!
