### ISSUE TITLE
Source for iiwa 7 inertia parameters

### ISSUE THREAD

**Issue by wiewo** [IFL-CAMP/iiwa_stack#123]
Hi,

e2bb3ed6 added approximations for the iiwa 7 inertia values without mentioning the source, only that they come from a paper. Do you know which paper is meant in the commit message?

I found a paper that determined them for the iiwa 14, but none for iiwa 7.

**Comment by SalvoVirga** [comment]
I believe those values are taken from http://www.inacomm2015.ammindia.org/img/94.pdf

Although checking now I also found this one: https://www.sciencedirect.com/science/article/pii/S2405896317317147

I might give a read later on and check.

**Comment by wiewo** [comment]
Thanks a lot, Salvo! I was not aware of the first one.

**Comment by matthiashh** [comment]
**iiwa 14**
The iiwa 14 values here seem to come from [the lbr_iiwa project](https://github.com/rtkg/lbr_iiwa/blob/master/lbr_iiwa_description/urdf/lbr_iiwa.xacro) .

Looking at the history of the values in that repo, there are changes here and there, but it's never mentioned where the values come from. Maybe it's worth asking him for a source, but as of now I don't see why they are preferred over the values in the paper Salvo quoted.

**iiwa 7**
The values come from the paper Salvo quoted. I am mostly wondering about the mass of the 7th link. For the iiwa 14 model it has been identified to ~0.3 kg whereas on the iiwa 7 it should be more than 3 kg. But taking a look at the paper for the 7 kg robot, they also seem to have mounted something to their flange.

**Document sources**
Anyhow, should we document the sources of the values in the xacro files?
