### ISSUE TITLE
IP Address for new Sunrise project

### ISSUE THREAD

**Issue by mattcorsaro1** [IFL-CAMP/iiwa_stack#126]
The third set-up step is `surise_project_setup`, described [here](https://github.com/IFL-CAMP/iiwa_stack/wiki/sunrise_project_setup). When creating a new Sunrise project, the IP address of the controller must be entered. What IP address should this be? This info would be useful in the wiki. Thanks.

**Comment by SalvoVirga** [comment]
That is a step specific to any Sunrise Workbench project, not linked to the use of iiwa_stack per se. The official documentation from KUKA should clarify that.

The IP of the robot may vary (if it was modified beforehand). The default one should be 172.31.1.147 on any robot and it can be modified within the Sunrise project, again this is all described in the documentation from KUKA.

I will add the default IP address to the wiki.

**Comment by mattcorsaro1** [comment]
Thanks!
