### ISSUE TITLE
Question: Kinematic accuracy of iiwa URDF

### ISSUE THREAD

**Issue by iSaran** [IFL-CAMP/iiwa_stack#129]
Has anybody used the iiwa 14 URDF for a long period of time in order to validate its kinematic accuracy? We used some other models for the IIWA and the F/K model produce different values from the URDF (around 1 cm error, dependent on the joint configuration). We do not have any ground truth so we need to trust the community's experience :)

**Comment by exo-core** [comment]
Hi @iSaran,

I've been playing around with Cartesian motions recently. Assuming that the kinematics model used by Sunrise ships properly calibrated you could run the following test:

1.  Select a cartesian target position for the flange and move the arm there via MoveIt! (or just read out it's current position)
2.  Convert your pose to the frame of your arm base (usually `iiwa_link_0`)
3.  Trigger a motion to the same pose via Sunrise and measure the difference.

There are some ROS actions to trigger those motions via Sunrise available on my [fork](https://github.com/exo-core/iiwa_stack) of iiwa_stack. From my experience the EE moves around 1-2 Millimeters but I never measured it exactly.

As an offset of around 1cm seems to be quite a lot: Are you using the same flange as in the URDF? The electric touch and pneumatic touch ones are a bit longer than the standard ones without the LEDs.

**Comment by SalvoVirga** [comment]
Just tried out the iiwa14 URDF together with a real robot and the FK results were correct. Robot and URDF had both an electric flange.
