### ISSUE TITLE
Cartesian control generates errors in loop

### ISSUE THREAD

**Issue by michtesar** [IFL-CAMP/iiwa_stack#133]
I face error when using cartesian control. I compute some coordinates at the circle with a specific resolution. Then pass them into the cartesian planner and execute trajectory. I put executing of the plan into a while True loop to have infinite draw circles. After several (approx. 5) loops robot stops movement. When I observed what happened, I found that the robot starts at first position but joint space is slightly different, after several loops, joints get into the position that robot is not able to move anymore. 

Is there a way how to replicate movement exactly?

**Comment by exo-core** [comment]
Just to let you know: all interfaces for controlling the iiwa in Cartesian space now use a `iiwa_msgs/CartesianPose.msg` that allows to set the redundancy data.
