### ISSUE TITLE
sunrise 1.15.I have install servoing1.15.but The import com.kuka.connectivity.motionModel cannot be resolved

### ISSUE THREAD

**Issue by lihx108** [IFL-CAMP/iiwa_stack#138]
The import com.kuka.connectivity.motionModel cannot be resolved

**Comment by lihx108** [comment]
![qq 20181228170350](https://user-images.githubusercontent.com/29481510/50510098-586dc480-0ac3-11e9-9f7f-5351c7dfc997.png)

**Comment by lihx108** [comment]
oo..I made a mistake.sorry

**Comment by madhukartlr** [comment]
I am getting the same issue. Would you mind telling me how it can resolved? Thanks.

**Comment by lihx108** [comment]
> I am getting the same issue. Would you mind telling me how it can resolved? Thanks.

Do you install servoing1.15 by the correct steps? In [help]->[Install new software]->[add].......
![image](https://user-images.githubusercontent.com/29481510/60264038-d6951180-9914-11e9-8272-428032757c8e.png)

**Comment by madhukartlr** [comment]
Is it already inside the Sunrise workbench or do I need to ask KUKA for Sunrise.Servoing?

**Comment by SalvoVirga** [comment]
It doesn't come with a standard installation of Sunrise Workbench, you have to install the Servoing package additionally.
