### ISSUE TITLE
melodic build errors

### ISSUE THREAD

**Issue by emielke12** [IFL-CAMP/iiwa_stack#139]
I just upgraded to melodic, and I'm having trouble building iiwa_hw. I am getting an error:
```
/home/user/ros_ws/src/iiwa_stack/iiwa_hw/src/iiwa_hw.cpp:111:57: error: no match for ‘operator=’ (operand types are ‘boost::shared_ptr<const urdf::Joint>’ and ‘urdf::JointConstSharedPtr {aka std::shared_ptr<const urdf::Joint>}’)
     joint = urdf_model_.getJoint(device_->joint_names[i]);
```
Wondering if melodic is supported, or if there's something obvious I am missing. Working off of a fork of master branch, and I am up to date.

**Comment by matthiashh** [comment]
As the line above says, I created a pull request that incorporates all the changes mentioned in my last comment.

I'd take this as a starting point to see if we can merge those commits into the master branch, but I neither have a good understanding of the code yet, nor do I have other ROS versions that `melodic` running here.

**Comment by matthiashh** [comment]
I pulled master after #142 has been merged and it builds on my machine.
So the issue seems to be resolved, but I can't close it.
