### ISSUE TITLE
Example for ActiveTool Implementation

### ISSUE THREAD

**Issue by exo-core** [IFL-CAMP/iiwa_stack#144]
https://github.com/IFL-CAMP/iiwa_stack/blob/14651865c524f46417df87a3ff10ace5cc0752ed/iiwa_ros_java/src/de/tum/in/camp/kuka/ros/app/ROSBaseApplication.java#L105-L111

The example implementation can be found [here](https://github.com/exo-core/iiwa_stack_tools) :wink:

**Comment by SalvoVirga** [comment]
thanks a lot, added it to the comment with 660e7a1
