### ISSUE TITLE
development branch: callback of the state holders leads to a run time exception

### ISSUE THREAD

**Issue by chenhaowen01** [IFL-CAMP/iiwa_stack#154]
The new callback function of state holders introduced at [commint](https://github.com/IFL-CAMP/iiwa_stack/commit/6dd6d5491e1f36d7a3e718f1a7d1667afe6bb527), will lead to a run time exception when launch the iiwa_hw node:

```shell
[ INFO] [1551443351.617159176]: Registering state and effort interfaces
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
```
After commenting [this line](https://github.com/IFL-CAMP/iiwa_stack/blob/development/iiwa_ros/include/iiwa_ros/iiwa_ros.hpp#L79), the run time error disappears.

I think of it is because callable object `callback_` is called before initialization (https://github.com/IFL-CAMP/iiwa_stack/blob/development/iiwa_ros/include/iiwa_ros/iiwa_ros.hpp#L79). But the strage thing is it is seems no code calls this function.

**Comment by SalvoVirga** [comment]
Thanks a lot for noticing! It should be now fixed
