### ISSUE TITLE
Robot model is messed up in RVIZ / melodic

### ISSUE THREAD

**Issue by exo-core** [IFL-CAMP/iiwa_stack#175]
Hi all,

I just tried to run our existing robot URDF in a melodic workspace. When launching our MoveIt! configuration (`roslaunch tum_iiwa_zimmer_r840_moveit moveit_planning_execution.launch`) the robot looks fine in Gazebo:

![Bildschirmfoto vom 2019-05-24 09-28-23](https://user-images.githubusercontent.com/35925786/58310608-50fadf00-7e07-11e9-9726-127305e3809c.png)

Also the TF tree is looking fine to me. However all 3d markers and meshes in our worcell are just randomly lying on the floor:

![Bildschirmfoto vom 2019-05-24 09-29-48](https://user-images.githubusercontent.com/35925786/58310625-607a2800-7e07-11e9-8f54-71c6cc1a1852.png)

Did anybody experience a similar issue and has a clue where it is coming from?

Ideas & Observations:
*  We already tried to set-up a new MoveIt! description but the problem was the same
*  Could it be an issue that the `joint_state` of our gripper fingers is not available in the simulation (in kinetic RVIZ just did not show the fingers...)?
*  Do I need to update something due to TF2?

**Comment by matthiashh** [comment]
Does the solution of #164  work for you?

**Comment by exo-core** [comment]
Indeed it does! Thanks! :smiley:
