### ISSUE TITLE
Sunrise project setup errors

### ISSUE THREAD

**Issue by isabellahuang** [IFL-CAMP/iiwa_stack#182]
I'm following the steps [here ](https://github.com/IFL-CAMP/iiwa_stack/wiki/sunrise_project_setup)to set up the Sunrise project to use iiwa_stack. However, I have an error (Sunrise Workbench v 1.10) and I was just wondering if removing the hint parameter to fix the problem is fine. Thanks!

![iiwa_error](https://user-images.githubusercontent.com/22259870/59377122-6bd5ba80-8d06-11e9-93f1-cf91066fcab2.PNG)

**Comment by SalvoVirga** [comment]
The error shows that the version of rosjava that you have in your build path is not the correct one. Be sure to remove the current libraries in the **ROSJavaLib** folder, delete the folder and then copy/link the one that comes with the latest version of the code.

**Comment by isabellahuang** [comment]
Thank you, I made a fresh project and refreshed the libraries. It works now!
