### ISSUE TITLE
Cannot Install ROSSmartServo

### ISSUE THREAD

**Issue by RagPrE** [IFL-CAMP/iiwa_stack#184]
I followed the instructions of setting up the sunrise cabinet, but I still cannot find the ROSSmartServo application on the pad and I got a compiler error on the sunrise workbench. I do not know where I miss the step. Could anyone give me some instructions on how to resolve this issue?

The followings are the screenshots of my current sunrise workbench.
  **compiler error: & workbrench**
![image](https://user-images.githubusercontent.com/51908423/59593703-ffebbb80-9124-11e9-895a-d8f5a15f7f88.png)

**my RoboticsAPI.data.xml**
![image](https://user-images.githubusercontent.com/51908423/59593759-1c87f380-9125-11e9-83c4-7110494bbd44.png)

**software options on station setup.cat**
![image](https://user-images.githubusercontent.com/51908423/59593993-899b8900-9125-11e9-8cef-e0273b0d3c78.png)

**Comment by SalvoVirga** [comment]
I see a red exclamation mark on the Sunrise Project, is there any item in the Error panel on Sunrise Workbench?

**Comment by RagPrE** [comment]
> I see a red exclamation mark on the Sunrise Project, is there any item in the Error panel on Sunrise Workbench?

INo, I can install this project without any problems, but the ROSSmartServo is still missing on the panel.

**Comment by SalvoVirga** [comment]
That is strange, try to refresh the project (Right Click on it -> Refresh) and see it that exclamation mark goes away. Maybe try to reinstall the project and then sync it, or make a new project from scratch, install that, sync that, then apply the modification needed for iiwa_stack and resync.

**Comment by RagPrE** [comment]
> That is strange, try to refresh the project (Right Click on it -> Refresh) and see it that exclamation mark goes away. Maybe try to reinstall the project and then sync it, or make a new project from scratch, install that, sync that, then apply the modification needed for iiwa_stack and resync.

Here, you can see the error message went away, but I still cannot found the application on the panel.
![image](https://user-images.githubusercontent.com/51908423/59601937-1b13f680-9138-11e9-87b4-424a466924b1.png)

One additional warning:
![image](https://user-images.githubusercontent.com/51908423/59602016-4860a480-9138-11e9-9bbc-8defe0539a1d.png)

**Comment by SalvoVirga** [comment]
You synced the project after installing it, right?
You can also try to create a dummy RoboticApplication, empty, unrelated to iiwa_stack and sync again, that should appear.

If all of that doesn't work, please try to create a new project and add the demo RoboticApplications that ship with Sunrise Workbench, sync the project and those application have to appear.

**Comment by RagPrE** [comment]
> You synced the project after installing it, right?
> You can also try to create a dummy RoboticApplication, empty, unrelated to iiwa_stack and sync again, that should appear.
> 
> If all of that doesn't work, please try to create a new project and add the demo RoboticApplications that ship with Sunrise Workbench, sync the project and those application have to appear.

**Comment by RagPrE** [comment]
> You synced the project after installing it, right?
> You can also try to create a dummy RoboticApplication, empty, unrelated to iiwa_stack and sync again, that should appear.
> 
> If all of that doesn't work, please try to create a new project and add the demo RoboticApplications that ship with Sunrise Workbench, sync the project and those application have to appear.

I forgot to synced. Maybe that is the problem. I will try that later.

**Comment by RagPrE** [comment]
> You synced the project after installing it, right?
> You can also try to create a dummy RoboticApplication, empty, unrelated to iiwa_stack and sync again, that should appear.
> 
> If all of that doesn't work, please try to create a new project and add the demo RoboticApplications that ship with Sunrise Workbench, sync the project and those application have to appear.

Thanks for your help.

**Comment by BossaMelon** [comment]
> > You synced the project after installing it, right?
> > You can also try to create a dummy RoboticApplication, empty, unrelated to iiwa_stack and sync again, that should appear.
> > If all of that doesn't work, please try to create a new project and add the demo RoboticApplications that ship with Sunrise Workbench, sync the project and those application have to appear.
> 
> Thanks for your help.

Can Sunrise Workbench support Chinese Language?
