### ISSUE TITLE
workplace build issue

### ISSUE THREAD

**Issue by chunxuli90** [IFL-CAMP/iiwa_stack#189]
Hi there

I am a new user of ROS. I am trying to build your project (iiwa_stack) to control kuka iiwa robot. I followed your instruction and got issue in the catkin build step. Could you please help? The info is shown below:

robotuser@RobotPC:~/iiwa_stack_ws$ catkin build
------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/melodic
Workspace:                   /home/robotuser/iiwa_stack_ws
------------------------------------------------------------------
Build Space:        [exists] /home/robotuser/iiwa_stack_ws/build
Devel Space:        [exists] /home/robotuser/iiwa_stack_ws/devel
Install Space:      [unused] /home/robotuser/iiwa_stack_ws/install
Log Space:          [exists] /home/robotuser/iiwa_stack_ws/logs
Source Space:       [exists] /home/robotuser/iiwa_stack_ws/src
DESTDIR:            [unused] None
------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------
[build] Found '7' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild                                            
_______________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/robotuser/iiwa_stack_ws/logs/catkin_tools_prebuild/build.cmake.010.log
CMake Error: The source directory "/home/robotuser/iiwa_stack_ws/build/catkin_tools_prebuild/--no-warn-unused-cli" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
cd /home/robotuser/iiwa_stack_ws/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/local/bin/cmake /home/robotuser/iiwa_stack_ws/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/robotuser/iiwa_stack_ws/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/robotuser/iiwa_stack_ws/install; cd -
...............................................................................
Failed     << catkin_tools_prebuild:cmake          [ Exited with code 1 ]      
Failed    <<< catkin_tools_prebuild                [ 0.0 seconds ]             
Abandoned <<< iiwa_control                         [ Unrelated job failed ]    
Abandoned <<< iiwa_description                     [ Unrelated job failed ]    
Abandoned <<< iiwa_gazebo                          [ Unrelated job failed ]    
Abandoned <<< iiwa_msgs                            [ Unrelated job failed ]    
Abandoned <<< iiwa_ros                             [ Unrelated job failed ]    
Abandoned <<< iiwa_hw                              [ Unrelated job failed ]    
Abandoned <<< iiwa_moveit                          [ Unrelated job failed ]    
[build] Summary: 0 of 8 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 7 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.1 seconds total.               

Thank you for your time.

Regards
Chunxu

**Comment by SalvoVirga** [comment]
You have some issues in your ROS installation. Maybe you did not complete the last installation steps?

Please be sure to go over the [ROS tutorials for beginners](http://wiki.ros.org/ROS/Tutorials). If you manage to build those, iiwa_stack should build normally as well.
