### ISSUE TITLE
Can Servo Motion packages be instead by FRI?

### ISSUE THREAD

**Issue by chunxuli90** [IFL-CAMP/iiwa_stack#195]
Hi Salvo,

I don't have the Servo Motion packages and just wondering can it be replaced by others such as FRI? Is the Sunrise Project still able to setup correctly without this package?

Thanks for your time!

**Comment by SalvoVirga** [comment]
No, currently not possible. You will need the Servoing package to use this repo.
There are [some attempts to also control the robot via FRI](https://github.com/CNR-STIIMA-IRAS/iiwa_stack), but not on the main repo yet.

**Comment by chunxuli90** [comment]
Hi Salvo, would it be possible that you send the Servoing package to me?

**Comment by SalvoVirga** [comment]
I'm sorry, but I cannot share Sunrise modules from KUKA. They are sold by KUKA and come with their own licensing.
