### ISSUE TITLE
Interference joint control with other repository (qbRobotics)

### ISSUE THREAD

**Issue by RoboticsKULeuven** [IFL-CAMP/iiwa_stack#213]
Dear,

We try to use iiwa_stack together with https://bitbucket.org/qbrobotics/qbhand-ros/src/production-melodic/

When both repositories reside in the same catkin workspace an error occured when trying to launch the qb_hand controller. It appears that in your `iiwa_hw/iiwa_hw_plugin.xml` file the class is closed badly. The '/' behind `...base_class_type="hardware_interface::RobotHW"/>` should be removed and at the bottom the class should be closed with `</class>` instead of `<class/>`

**Comment by SalvoVirga** [comment]
Good catch, hotfixing it

**Comment by SalvoVirga** [comment]
Could you check if #215 solves the issue?

**Comment by RoboticsKULeuven** [comment]
Checked out your branch and it works!
