### ISSUE TITLE
Quick question about X66 port connection

### ISSUE THREAD

**Issue by XuanliangDeng** [IFL-CAMP/iiwa_stack#223]
Hi all,
I am new to KUKA and iiwa_stack right now I could successfully compile iiwa_stack and run simulation in ROS Kinetic on my PC (step3). But I had problems with step 1.

When I connect the ethernet cable from X66 port to my ROS machine, my machine always said ethernet network is disconnected. Do I need any extra modules for KUKA to connect to my PC(Besides ubuntu 16 and ROS Kinetic)?

Thank you for your help in advance.

**Comment by matthiashh** [comment]
Usually your network interface is configured to receive an IP address via DHCP.

If you connect your machine and the cabinet directly the easiest should be to configure the network interface manually and assign a static IP address within the same subnet as the cabinets address  - e.g. like [this](https://help.ubuntu.com/lts/ubuntu-help/net-manual.html.en).
