### ISSUE TITLE
Dart physics engine incompatibility

### ISSUE THREAD

**Issue by arturShafikov** [IFL-CAMP/iiwa_stack#243]
Hi everyone!
I'm trying to launch simulation via `roslaunch iiwa_moveit moveit_planning_execution.launch` with Dart physics engine however after I set target pose via RViz and try to _Plan and Execute_ it, the model executes most of the motions and right when it reaches target pose instead of stopping it starts to spin chaotically and then collapses (see the attached picture). At this point for each link (i.e. 1 to 7) the following errors start to pop up:
`Ignoring transform for child_frame_id "iiwa_link_1" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)`
![default_gzclient_camera(1)-2020-03-27T10_50_08 551533](https://user-images.githubusercontent.com/51114048/77734845-7f92a900-701a-11ea-9dd8-2700d4669e71.jpg)

I should probably mention the following:
- When using ODE physics engine everything works perfectly well.
- There are two errors when launching `moveit_planning_execution`:
     1. `No p gain specified for pid.  Namespace: /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_1` -                  this one appears when I use ODE physics engine as well (and it still works). I tried [this](https://github.com/IFL-CAMP/iiwa_stack/issues/161) and [this](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/886) solutions but they didn't work for me. But as far as I understood this warning means that some default Gazebo behavior will be used. 
     2. `ROS get_physics_properties service call does not yet support physics engine [dart].`
- Once in a while KUKA manages to complete first trajectory execution and let me choose the next state, but then collapses anyway.
- I have **real time factor** < 0.1 when using Dart. I was able to reach ~0.3 by placing manipulator on the box as shown in [this](https://github.com/IFL-CAMP/iiwa_stack/wiki/createmoveit) example but the problem still remains.
- I use Ubuntu 18.04 with ROS Melodic and Gazebo-9.

Has anyone experienced such a problem before or used Dart engine with iiwa_stack successfully?
Or maybe someone had similar problem and knows how to solve it?

Any help and feedback would be appreciated, thanks in advance!

**Comment by huangdii** [comment]
how to solve the problem? I have same issue :(

**Comment by arturShafikov** [comment]
> how to solve the problem? I have same issue :(

Hello, Huangdii!
It's been a while so I might be wrong, but as far as I remember, changing _joint_damping_ value in _iiwa_description/urdf/iiwa14.xacro_ or in _iiwa_description/urdf/iiwa7.xacro_  to 10.0 for example (instead of 0.5) solves the problem. I think it's not correct for this value to be lower than 1.0. 
If it's not the case, feel free to write againg, I'll try to think of something else.
