### ISSUE TITLE
[ERROR]configuration/configureSmartServo could not be called

### ISSUE THREAD

**Issue by MengChao1** [IFL-CAMP/iiwa_stack#98]
I want to change the control mode. so I try to roslaunch "/iiwa_tool_examples/launch/iiwa_tool_control_mode.launch" I get the error. I don't know why,  Thank you.

**Comment by SalvoVirga** [comment]
Do you see the service `/iiwa/configuration/configureSmartServo` being advertised when running `rosservice list` ?
Those examples are very old, probably not valid anymore.

**Comment by MengChao1** [comment]
Thanks for your answer. Now I have another question. Can I use the "/iiwa/configuration/configureSmartServo" service in gazebo?  When I "rosservice list" I can't find it?

**Comment by SalvoVirga** [comment]
No sorry, that service is advertised directly by the robot controller, it will not exist in simulation. You would have to use the interfaces offered by Gazebo for that.

**Comment by MengChao1** [comment]
Thanks for your reply
